# Generated by Django 5.2.4 on 2025-07-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='temp_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
